### ISSUE TITLE
Errors with Admin FE

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/akkoma_ynh#11]
At login:

```
Request failed with status code 500 - [object Object]
```

If I want to install a frontend (SB):

```
Request failed with status code 500 - [object Object]
```

Installed Fedibird FE but no way to activate...

**Comment by lapineige** [comment]
I had the same issue.

According to `service akkoma status`, seems to be related to a syntax error (??) in the `/etc/akkoma/config.exs` file, with this line:
`config :akkoma, Akkoma.Web.Auth.Authenticator, Akkoma.Web.Auth.LDAPAuthenticator`

I commented it, it works.

Can you try too ?

Meanwhile, you can setup your "primary" frontend in this config file… oh wait because of the error you probably can't.

**Comment by bugsysop** [comment]
```
Pleroma.Web.Auth.Authenticator
```
See here:
https://docs.akkoma.dev/stable/configuration/cheatsheet/#pleromawebauthauthenticator

**Comment by lapineige** [comment]
Well, I still don't get where there should be any syntax error.
Unless there could be only one of the two options, but then who doesn't it fail on Pleroma_ynh ?

**Comment by bugsysop** [comment]
It’s `Pleroma` not `Akkoma`... if I understand the documentation

Try to replace `Akkoma.Web.Auth.Authenticator` with `Pleroma.Web.Auth.Authenticator`
